---

- stat: path=/tmp/swarm_init
  register: swarm_init

- name: Initalize the Swarm
  shell: docker swarm init
  args:
    creates: /tmp/swarm_init

- name: Create a file in /tmp so we don't try and initalize the Swarm again
  file:
    path: "/tmp/swarm_init"
    mode: "u=rw,g=r,o=r"
    state: "{{ 'file' if swarm_init.stat.exists else 'touch' }}"